#This is m process of creating an s3 bucket using cloud formation.
#4/13/25o
# X.com  @johnwmintz

AWSTemplateFormatVersion: "2010-09-09" 
Description: Simple cloud formation for s3 bucket creation and configuration